export const FETCH_PRODUCTS_LOADING = "FETCH_PRODUCTS_LOADING" ;
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";

export const INDIVIDUAL_DATA_LOADING = "INDIVIDUAL_DATA_LOADING"
export const INDIVIDUAL_DATA_SUCCESS = "INDIVIDUAL_DATA_SUCCESS"
export const INDIVIDUAL_DATA_FAIL = "INDIVIDUAL_DATA_FAIL"